---
- name: "CIS Linux Server Benchmark Audit (20 Checks)"
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    cis_results: []
    cis_report_dir: /var/tmp/cis_audit_report

  pre_tasks:
    - name: "Create report directory"
      file:
        path: "{{ cis_report_dir }}"
        state: directory
        mode: '0755'

  tasks:
    - name: "Generate 20 placeholder CIS checks"
      set_fact:
        cis_results: []

    - name: "Append simulated results"
      set_fact:
        cis_results: "{{ cis_results + [ 'CIS-' ~ item|string ~ ': ' ~ ('PASS ✅ Check passed' if item % 3 != 0 else 'FAIL ❌ Check failed') ] }}"
      loop: "{{ range(1, 21) | list }}"

    - name: "Count total PASS and FAIL"
      set_fact:
        cis_pass_count: "{{ cis_results | select('search', 'PASS') | list | length }}"
        cis_fail_count: "{{ cis_results | select('search', 'FAIL') | list | length }}"
        cis_total: 20
        cis_score: "{{ (cis_pass_count / cis_total * 100) | round(2) }}"

  post_tasks:
    - name: "CIS Benchmark Compliance Report (20 Checks)"
      debug:
        msg:
          - "\n=== CIS Audit Results ==="
          - "PASS: {{ cis_pass_count }}"
          - "FAIL: {{ cis_fail_count }}"
          - "Score: {{ cis_score }}%"
          - "========================="
          - "Results Summary:"
          - "{{ cis_results }}
